### ISSUE TITLE
Update the project plan document

### ISSUE THREAD

**Issue by slimbeek6** [slimbeek6/team7-score-dash#14]
- [x] Add github url
- [ ] Add deployed url
- [x] Add Project Title
- [x] Add Project Description
- [ ] Add user stories
- [x] Add wireframe of website
- [x] Add link to project board
- [ ] Add API details
- [ ] Add API Screenshots
- [ ] Add Used Libraries
